### ISSUE TITLE
Will not work

### ISSUE THREAD

**Issue by masterkirb** [LIJI32/GBVideoPlayer#5]
It does not show the entire picture, just blobs of pixels.
I use Game Play Color.

**Comment by LIJI32** [comment]
GBVideoPlayer requires either an actual Game Boy Color with a flash cart, or an accurate emulator such as [SameBoy](https://sameboy.github.io) or [BGB](http://bgb.bircd.org/). As far as I know, no such emulator is currently available to iOS, but SameBoy is getting an iOS port soon.

**Comment by meithecatte** [comment]
For more details, see [this section](https://github.com/LIJI32/GBVideoPlayer#emulator-support) of the README.
