### ISSUE TITLE
How Do you compose to the music.itt file?

### ISSUE THREAD

**Issue by holadivinus** [LIJI32/GBVideoPlayer#7]
I've been looking through the code and trying to get it to do what i want. now, i kust need to know how the music works.
Sample from the file:
```
|E-401v26...|D-501v26...|G-301......|...........
|...........|...........|...........|C-506......
|.....v21...|.....v21...|...........|...........
|...........|...........|...........|...........
|.....v17...|.....v17...|...........|...........
|...........|...........|...........|...........
|...........|...........|...........|...........
|...........|...........|...........|...........
```

If you change the first letter (E-) to something like E#, the compilation process errors with:

`["C-", "C#", "D-", "D#", "E-", "F-", "F#", "G-", "G#", "A-", "A#", "B-"]`

and

`E# is not in the list`

I've inferred that these note's are whats possible. BUT, WHAT DOES ALL OF the other stuff mean????

`:/`

**Comment by LIJI32** [comment]
This is the same format module trackers (such as OpenMPT) use, with some Game Boy specific restrictions. E# (E sharp) is equivalent to F- (F) so it's not used by trackers.

**Comment by holadivinus** [comment]
Cool, i'll look into it. thnx
